services:
  - type: web
    name: college-event-hub
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://tanushreekumbhare11_db_user:LAUOMNrXqnGuwTaJ@cluster0.bvf4swb.mongodb.net/college_event_hub?retryWrites=true&w=majority
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        value: college_event_hub_production_session_secret_render_2026
